export const dummyData = [
  {
    id: "card-1",
    title: "Art of thinking clearly",
    author: "Rolf Dobelli",
    quote: `How do you curb envy? First, stop comparing yourself to others. Second, find your “circle of competence” and fill it on your own. Create a niche where you are the best. It doesn’t matter how small your area of mastery is. The main thing is that you are king of the castle.`,
    review: `A world-class thinker counts the 100 ways in which humans behave irrationally, showing us what we can do to recognize and minimize these “thinking errors” to make better decisions and have a better`,
    date: "10/23/2022",
    userName: "farhad gh",
    userAvatar: "https://wallpaperaccess.com/full/4595683.jpg",
    numOfLikes: 24,
    numOfDislikes: 24,
    isSaved: true,
    isLiked: true,
  },
  {
    id: "card-2",
    title: "It Ends with Us",
    author: "Colleen Hoover",
    quote: `All humans make mistakes. What determine a person’s character aren’t the mistakes we make. It is how we take those mistakes and turn them into lessons rather than excuses.`,
    review: `I devoured this book in literally, no exaggeration, six hours. I spent six hours straight just eating up the content of this book. And I think it's safe to say those six hours changed my life.`,
    date: "10/23/2022",
    userName: "Hana Fayed",
    userAvatar:
      "https://i.pinimg.com/474x/67/b1/d6/67b1d617a51467eea5b606e4f4445a34.jpg",
    numOfLikes: 10,
    numOfDislikes: 0,
    isLiked: true,
  },
  {
    id: "card-3",
    title: "Atomic Habits",
    author: "James Clear",
    review: `This is a masterpiece, If you are at that point of your life where you have failed, given up and feeling low and depressed, here is something for you which will not only lift up your spirits but bring you right on the path of success.`,
    date: "10/23/2022",
    userName: "Ammit P Chawda",
    userAvatar:
      "https://cdna.artstation.com/p/assets/images/images/053/054/138/large/avetetsuya-studios-alien.jpg?1661309922",
    numOfLikes: 584,
    numOfDislikes: 5,
    isDisliked: true,
  },
  {
    id: "card-4",
    title: "Verity",
    author: "Colleen Hoover",
    quote: `How do you curb envy? First, stop comparing yourself to others.`,
    date: "10/23/2022",
    userName: "Guest User",
    userAvatar:
      "https://qph.cf2.quoracdn.net/main-qimg-54166a525ee4fb3097d260173688c157.webp",
    numOfLikes: 0,
    numOfDislikes: 16,
    isLiked: true,
  },

  {
    id: "card-5",
    title: "Atomic Habits",
    author: "James Clear",
    review: `This is a masterpiece, If you are at that point of your life where you have failed, given up and feeling low and depressed, here is something for you which will not only lift up your spirits but bring you right on the path of success.`,
    date: "10/23/2022",
    userName: "Ammit P Chawda",
    userAvatar:
      "https://www.pngitem.com/pimgs/m/192-1926160_transparent-ajax-png-anime-profile-png-download.png",
    numOfLikes: 584,
    numOfDislikes: 5,
    isSaved: true,
    isLiked: true,
  },
  {
    id: "card-6",
    title: "Art of thinking clearly",
    author: "Rolf Dobelli",
    quote: `How do you curb envy? First, stop comparing yourself to others. Second, find your “circle of competence” and fill it on your own. Create a niche where you are the best. It doesn’t matter how small your area of mastery is. The main thing is that you are king of the castle.`,
    review: `A world-class thinker counts the 100 ways in which humans behave irrationally, showing us what we can do to recognize and minimize these “thinking errors” to make better decisions and have a better`,
    date: "10/23/2022",
    userName: "farhad gh",
    userAvatar:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsbQJi7hAKzJhIMkaxjIhHDWZ6i8TVSI9n8g&usqp=CAU",
    numOfLikes: 24,
    numOfDislikes: 24,
    isDisliked: true,
  },
  {
    id: "card-7",
    title: "Art of thinking clearly",
    author: "Colleen Hoover",
    quote: `How do you curb envy? First, stop comparing yourself to others. Second, find your “circle of competence” and fill it on your own. Create a niche where you are the best. It doesn’t matter how small your area of mastery is. The main thing is that you are king of the castle.`,
    date: "10/23/2022",
    userName: "Guest User",
    userAvatar:
      "https://divedigital.id/wp-content/uploads/2022/07/36-Anya-Just-Woke-Up-1024x1024.jpg",
    numOfLikes: 0,
    numOfDislikes: 16,
    isLiked: true,
  },
  {
    id: "card-8",
    title: "It Ends with Us",
    author: "Colleen Hoover",
    quote: `All humans make mistakes. What determine a person’s character aren’t the mistakes we make. It is how we take those mistakes and turn them into lessons rather than excuses.`,
    review: `I devoured this book in literally, no exaggeration, six hours. I spent six hours straight just eating up the content of this book. And I think it's safe to say those six hours changed my life.`,
    date: "10/23/2022",
    userName: "Hana Fayed",
    userAvatar:
      "https://fsb.zobj.net/crop.php?r=E1yX8GF6csvRtPGMlPDTsN-zFkaEft0dXZ0Iwoh9omBMsCorpgraEY9GxM8x_BszUrUz9rIMW8zRxx-TgEzDh1sGC51n-binIGnUGLnSg3WsiOB83lR0LQivxlRtavOd9gefVmhoL-iJqPF0I59j8OfosQkp7Cbrb90tbJt9G5scUQQOdydmGn4C4mY",
    numOfLikes: 10,
    numOfDislikes: 0,
    isSaved: true,
  },
  {},
];
